### ISSUE TITLE
EVENT: Oneshot Night

### ISSUE THREAD

**Issue by Bork114** [Zorth/TarragonWeb#8]
## Venturer:
@BrenainnVanhaverbeke 

## Absent:
-

## Roles:

Photographer:
Crowd Control:
Time Table Tracker (s):

## Time Table:

_Place Drive link to timetable here_

## Material:

**Comment by BrenainnVanhaverbeke** [comment]
Contacted volunteers.
- Patrick (akadeax)
- Lukas (oldsprite)
- Bert Van Hoorick (cmmbert)
- Viktor (lazage)
- Amber (alynxx)
- Caia (shadowcaia)

Confirmed:
- Patrick: The Delian Tomb

Pending: 
- Lukas (Waiting for appeal approval. It's DAE, so don't think it'll happen.)
- Amber (No reply yet)
- Bert VH (Is interested, just thinking about specifics. Marked as pending.)

Newp:
- Viktor
- Caia
